/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica.Nieves.Chuquipoma.vista.Disco;

import ec.edu.ups.practica.Nieves.Chuquipoma.controlador.ControladorCantante;
import ec.edu.ups.practica.Nieves.Chuquipoma.modelo.Cantante;
import ec.edu.ups.practica.Nieves.Chuquipoma.modelo.Disco;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class EliminarDisco extends javax.swing.JInternalFrame {
    private ControladorCantante controladorCantante;
    private Cantante cantanteTempo;
    private Disco disco;
    /**
     * Creates new form EliminarDisco
     */
    public EliminarDisco(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtIdCantante4 = new javax.swing.JTextField();
        bntBuscar4 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        txtNombre4 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtApellido4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtEdad4 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtNombreArtistico4 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtCodigo4 = new javax.swing.JTextField();
        txtNombreDisco4 = new javax.swing.JTextField();
        txtAnioLanzamiento4 = new javax.swing.JTextField();
        bntCancelar4 = new javax.swing.JButton();
        bntBuscarDisco = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Disco"));

        jLabel37.setText("Buscar cantante para encontar disco : ");

        bntBuscar4.setText("Buscar");
        bntBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscar4ActionPerformed(evt);
            }
        });

        jLabel38.setText("Ingrese el nombre del disco");

        txtNombre4.setEditable(false);
        txtNombre4.setEnabled(false);
        txtNombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre4ActionPerformed(evt);
            }
        });

        jLabel39.setText("Nombre : ");

        jLabel40.setText("Apellido :");

        txtApellido4.setEditable(false);
        txtApellido4.setEnabled(false);

        jLabel41.setText("Edad :");

        txtEdad4.setEditable(false);
        txtEdad4.setEnabled(false);

        jLabel42.setText("Nombre artistico :");

        txtNombreArtistico4.setEditable(false);
        txtNombreArtistico4.setEnabled(false);

        jLabel43.setText("Codigo :");

        jLabel44.setText("Nombre :");

        jLabel45.setText("Año de lanzamiento :");

        txtCodigo4.setEnabled(false);
        txtCodigo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo4ActionPerformed(evt);
            }
        });

        txtNombreDisco4.setEnabled(false);
        txtNombreDisco4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDisco4ActionPerformed(evt);
            }
        });

        txtAnioLanzamiento4.setEnabled(false);
        txtAnioLanzamiento4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioLanzamiento4ActionPerformed(evt);
            }
        });

        bntCancelar4.setText("Cancelar");
        bntCancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelar4ActionPerformed(evt);
            }
        });

        bntBuscarDisco.setText("Buscar");
        bntBuscarDisco.setEnabled(false);
        bntBuscarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarDiscoActionPerformed(evt);
            }
        });

        bntEliminar.setText("Eliminar");
        bntEliminar.setEnabled(false);
        bntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel37))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIdCantante4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bntBuscar4)
                                            .addComponent(txtNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel38)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                                    .addComponent(jLabel41)
                                                                    .addGap(136, 136, 136))
                                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                    .addComponent(jLabel40)
                                                                    .addGap(110, 110, 110)))
                                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addComponent(jLabel42)
                                                                .addGap(43, 43, 43)))
                                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtNombreArtistico4)
                                                            .addComponent(txtApellido4)
                                                            .addComponent(txtEdad4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                                    .addComponent(jLabel45)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtAnioLanzamiento4, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                                    .addComponent(jLabel44)
                                                    .addGap(108, 108, 108)
                                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtCodigo4)
                                                        .addComponent(txtNombreDisco4, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))))
                                            .addGap(38, 38, 38)
                                            .addComponent(bntBuscarDisco))))
                                .addComponent(jLabel39))
                            .addGap(90, 90, 90))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(bntEliminar)
                            .addGap(60, 60, 60)
                            .addComponent(bntCancelar4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCantante4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscar4))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellido4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEdad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42)
                    .addComponent(txtNombreArtistico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel43)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bntBuscarDisco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(txtNombreDisco4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(txtAnioLanzamiento4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEliminar)
                    .addComponent(bntCancelar4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscar4ActionPerformed
        // TODO add your handling code here:
        if (txtIdCantante4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No esta lleno el campo ");
        }else{
            cantanteTempo = controladorCantante.buscarCantante(Integer.parseInt(txtIdCantante4.getText()));
            if (cantanteTempo!=null) {
                txtIdCantante4.setEnabled(false);
                this.mostrarDatos(cantanteTempo);
                bntBuscar4.setEnabled(false);
                bntBuscarDisco.setEnabled(true);
                txtCodigo4.setEnabled(true);

            }else{
                JOptionPane.showMessageDialog(this, "No existe "+ txtIdCantante4.getText()+" en cantantes. ");
            }
        }
    }//GEN-LAST:event_bntBuscar4ActionPerformed

    private void txtNombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre4ActionPerformed

    private void txtCodigo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo4ActionPerformed

    private void txtAnioLanzamiento4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioLanzamiento4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioLanzamiento4ActionPerformed

    private void bntCancelar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelar4ActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
        bntBuscar4.setEnabled(true);
        txtIdCantante4.setEnabled(true);
        bntBuscarDisco.setEnabled(false);
        txtCodigo4.setEnabled(false);
    }//GEN-LAST:event_bntCancelar4ActionPerformed

    public void limpiarCampos(){
        txtIdCantante4.setText("");
        txtNombreDisco4.setText("");
        txtApellido4.setText("");
        txtCodigo4.setText("");
        txtEdad4.setText("");
        txtNombreArtistico4.setText("");
        txtNombreDisco4.setText("");
        txtAnioLanzamiento4.setText("");
        txtNombre4.setText("");
    }
    public void mostrarDatos(Cantante cantante){
        txtIdCantante4.setEnabled(false);
        bntBuscar4.setEnabled(false);
        txtNombre4.setText(cantante.getNombre());
        txtEdad4.setText( String.valueOf(cantante.getEdad()));
        txtNombreArtistico4.setText(cantante.getNombreArtistico());
        txtApellido4.setText(cantante.getApellido());
        
    }
    
    
    private void bntBuscarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarDiscoActionPerformed
        // TODO add your handling code here:
        if (txtCodigo4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No esta lleno el campo ");
        }else {
            disco = cantanteTempo.buscarDisco(Integer.parseInt(txtCodigo4.getText()));
            if (disco!=null) {
                txtAnioLanzamiento4.setText(String.valueOf(disco.getAnioDeLanzamiento()));
                txtNombreDisco4.setText(disco.getNombre());
                bntEliminar.setEnabled(true);
            }else{
                txtAnioLanzamiento4.setText("");
                txtNombreDisco4.setText("");
                JOptionPane.showMessageDialog(this, "No se encuentra el disco el disco ");
                bntEliminar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_bntBuscarDiscoActionPerformed

    private void bntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarActionPerformed
        // TODO add your handling code here:
        int num = JOptionPane.showConfirmDialog(this, "Esta seguro que desea elimnar el disco "+ disco.getNombre());
        if (num == JOptionPane.YES_OPTION) {
            cantanteTempo.eliminarDisco(Integer.parseInt(txtCodigo4.getText()));
            bntEliminar.setEnabled(false);
            bntBuscarDisco.setEnabled(true);
            txtCodigo4.setEnabled(true);
            System.out.println(cantanteTempo);
            txtNombreDisco4.setText("");
            txtAnioLanzamiento4.setText("");
            txtCodigo4.setText("");
        }else{
            JOptionPane.showMessageDialog(this,"No se a eliminado correctamente ");
            txtNombreDisco4.setText("");
            txtAnioLanzamiento4.setText("");
            txtCodigo4.setText("");
        }
    }//GEN-LAST:event_bntEliminarActionPerformed

    private void txtNombreDisco4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDisco4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDisco4ActionPerformed
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar4;
    private javax.swing.JButton bntBuscarDisco;
    private javax.swing.JButton bntCancelar4;
    private javax.swing.JButton bntEliminar;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtAnioLanzamiento4;
    private javax.swing.JTextField txtApellido4;
    private javax.swing.JTextField txtCodigo4;
    private javax.swing.JTextField txtEdad4;
    private javax.swing.JTextField txtIdCantante4;
    private javax.swing.JTextField txtNombre4;
    private javax.swing.JTextField txtNombreArtistico4;
    private javax.swing.JTextField txtNombreDisco4;
    // End of variables declaration//GEN-END:variables

    public void cambiarIdioma(Locale localizacion) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
